name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to Heroku
        if: github.event_name == 'push'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HRKU-be08bb39-487b-406a-bba4-3ca1dff0191d}}  # Variable de entorno secreta con la API key de Heroku
          heroku_app_name: deber-apis  # Nombre de tu aplicación en Heroku
          heroku_email: gonzaloguachamin2330@gmail.com  # Correo electrónico asociado con tu cuenta de Heroku